---
title: "Getting Started"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r echo = FALSE}

knitr::opts_chunk$set(collapse = TRUE, comment = "#>")

# Use vertical split by default in this Rmd document
knit_print.htmlwidget <- function(x, ...) {
  # Get the chunk height
  height <- knitr::opts_current$get("height")
  if (length(height) > 0 && height != FALSE)
    x$height <- height
  else
    x$height <- "450px"

  htmlwidgets:::knit_print.htmlwidget(x, ...)
}
```

To install the first _preview_ release of **autoCaret** from GitHub:

```{r eval=FALSE}
devtools::install_github("gregce/autoCaret")
```

The RStudio IDE includes integrated support for using autoCaret as an add-in. These features are available in the current [Release of RStudio](https://www.rstudio.com/products/rstudio/download/).
Below are some examples of autoCaret in use. 

## Using `autoModel`


## Exploring an `autoCaret` object


## Making predictions using `autoCaret`





